# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EQEgui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1027, 696)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setSpacing(5)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.tab_6)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(5)
        self.splitter.setObjectName("splitter")
        self.mplwidget = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwidget.sizePolicy().hasHeightForWidth())
        self.mplwidget.setSizePolicy(sizePolicy)
        self.mplwidget.setObjectName("mplwidget")
        self.verticalLayout_mplwidget = QtWidgets.QVBoxLayout(self.mplwidget)
        self.verticalLayout_mplwidget.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_mplwidget.setSpacing(5)
        self.verticalLayout_mplwidget.setObjectName("verticalLayout_mplwidget")
        self.frame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(self.tab_4)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.tabWidget_left = QtWidgets.QTabWidget(self.splitter_2)
        self.tabWidget_left.setObjectName("tabWidget_left")
        self.spectrum = QtWidgets.QWidget()
        self.spectrum.setObjectName("spectrum")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.spectrum)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.pushButton_loadspectrum = QtWidgets.QPushButton(self.spectrum)
        self.pushButton_loadspectrum.setObjectName("pushButton_loadspectrum")
        self.gridLayout_13.addWidget(self.pushButton_loadspectrum, 1, 0, 1, 2)
        self.lineEdit_spectrumloaded = QtWidgets.QLineEdit(self.spectrum)
        self.lineEdit_spectrumloaded.setReadOnly(True)
        self.lineEdit_spectrumloaded.setObjectName("lineEdit_spectrumloaded")
        self.gridLayout_13.addWidget(self.lineEdit_spectrumloaded, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.spectrum)
        self.label_12.setObjectName("label_12")
        self.gridLayout_13.addWidget(self.label_12, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem, 2, 0, 1, 1)
        self.tabWidget_left.addTab(self.spectrum, "")
        self.Range = QtWidgets.QWidget()
        self.Range.setObjectName("Range")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Range)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_5 = QtWidgets.QLabel(self.Range)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 1, 0, 1, 1)
        self.doubleSpinBox_Xmin = QtWidgets.QDoubleSpinBox(self.Range)
        self.doubleSpinBox_Xmin.setMaximum(5000.0)
        self.doubleSpinBox_Xmin.setProperty("value", 300.0)
        self.doubleSpinBox_Xmin.setObjectName("doubleSpinBox_Xmin")
        self.gridLayout_7.addWidget(self.doubleSpinBox_Xmin, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.Range)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.Range)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 3, 1, 1, 1)
        self.doubleSpinBox_Ymin = QtWidgets.QDoubleSpinBox(self.Range)
        self.doubleSpinBox_Ymin.setMinimum(-1000.0)
        self.doubleSpinBox_Ymin.setMaximum(1000.0)
        self.doubleSpinBox_Ymin.setObjectName("doubleSpinBox_Ymin")
        self.gridLayout_7.addWidget(self.doubleSpinBox_Ymin, 4, 0, 1, 1)
        self.doubleSpinBox_Ymax = QtWidgets.QDoubleSpinBox(self.Range)
        self.doubleSpinBox_Ymax.setMinimum(-1000.0)
        self.doubleSpinBox_Ymax.setMaximum(1000.0)
        self.doubleSpinBox_Ymax.setProperty("value", 1.0)
        self.doubleSpinBox_Ymax.setObjectName("doubleSpinBox_Ymax")
        self.gridLayout_7.addWidget(self.doubleSpinBox_Ymax, 4, 1, 1, 1)
        self.doubleSpinBox_Xmax = QtWidgets.QDoubleSpinBox(self.Range)
        self.doubleSpinBox_Xmax.setMaximum(5000.0)
        self.doubleSpinBox_Xmax.setProperty("value", 1200.0)
        self.doubleSpinBox_Xmax.setObjectName("doubleSpinBox_Xmax")
        self.gridLayout_7.addWidget(self.doubleSpinBox_Xmax, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.Range)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 3, 0, 1, 1)
        self.checkBox_AutoScale = QtWidgets.QCheckBox(self.Range)
        self.checkBox_AutoScale.setObjectName("checkBox_AutoScale")
        self.gridLayout_7.addWidget(self.checkBox_AutoScale, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.Range)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_7.addWidget(self.comboBox, 0, 1, 1, 1)
        self.tabWidget_left.addTab(self.Range, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_SGFilter = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_SGFilter.setObjectName("pushButton_SGFilter")
        self.gridLayout_2.addWidget(self.pushButton_SGFilter, 0, 0, 1, 2)
        self.spinBox_SG1 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_SG1.setMaximum(999)
        self.spinBox_SG1.setProperty("value", 31)
        self.spinBox_SG1.setObjectName("spinBox_SG1")
        self.gridLayout_2.addWidget(self.spinBox_SG1, 1, 0, 1, 1)
        self.spinBox_SG2 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_SG2.setMaximum(999)
        self.spinBox_SG2.setProperty("value", 5)
        self.spinBox_SG2.setObjectName("spinBox_SG2")
        self.gridLayout_2.addWidget(self.spinBox_SG2, 1, 1, 1, 1)
        self.pushButton_goback = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_goback.setObjectName("pushButton_goback")
        self.gridLayout_2.addWidget(self.pushButton_goback, 2, 0, 1, 2)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.tabWidget_left.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_CalcCurrent = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_CalcCurrent.setObjectName("pushButton_CalcCurrent")
        self.gridLayout_6.addWidget(self.pushButton_CalcCurrent, 0, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinBox_from = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_from.setMaximum(9999)
        self.spinBox_from.setProperty("value", 320)
        self.spinBox_from.setObjectName("spinBox_from")
        self.gridLayout_6.addWidget(self.spinBox_from, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 1, 2, 1, 1)
        self.spinBox_to = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_to.setMaximum(9999)
        self.spinBox_to.setProperty("value", 1200)
        self.spinBox_to.setObjectName("spinBox_to")
        self.gridLayout_6.addWidget(self.spinBox_to, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 2, 0, 1, 2)
        self.doubleSpinBox_calcjsc = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_calcjsc.setDecimals(3)
        self.doubleSpinBox_calcjsc.setMinimum(-999.0)
        self.doubleSpinBox_calcjsc.setMaximum(999.0)
        self.doubleSpinBox_calcjsc.setObjectName("doubleSpinBox_calcjsc")
        self.gridLayout_6.addWidget(self.doubleSpinBox_calcjsc, 2, 2, 1, 2)
        self.comboBox_calccurrent = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_calccurrent.setObjectName("comboBox_calccurrent")
        self.gridLayout_6.addWidget(self.comboBox_calccurrent, 0, 2, 1, 2)
        self.tabWidget_left.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_stitchEQEs = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_stitchEQEs.setEnabled(False)
        self.pushButton_stitchEQEs.setObjectName("pushButton_stitchEQEs")
        self.gridLayout_4.addWidget(self.pushButton_stitchEQEs, 2, 0, 1, 1)
        self.checkBox_showsecreteg = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_showsecreteg.setObjectName("checkBox_showsecreteg")
        self.gridLayout_4.addWidget(self.checkBox_showsecreteg, 1, 0, 1, 1)
        self.tabWidget_left.addTab(self.tab_2, "")
        self.tabWidget_right = QtWidgets.QTabWidget(self.splitter_2)
        self.tabWidget_right.setObjectName("tabWidget_right")
        self.Selection = QtWidgets.QWidget()
        self.Selection.setObjectName("Selection")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.Selection)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.listWidget = QtWidgets.QListWidget(self.Selection)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_8.addWidget(self.listWidget, 0, 0, 1, 1)
        self.tabWidget_right.addTab(self.Selection, "")
        self.Legend = QtWidgets.QWidget()
        self.Legend.setObjectName("Legend")
        self.gridLayout = QtWidgets.QGridLayout(self.Legend)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_topleft = QtWidgets.QRadioButton(self.Legend)
        self.radioButton_topleft.setObjectName("radioButton_topleft")
        self.gridLayout.addWidget(self.radioButton_topleft, 1, 0, 1, 1)
        self.radioButton_topright = QtWidgets.QRadioButton(self.Legend)
        self.radioButton_topright.setObjectName("radioButton_topright")
        self.gridLayout.addWidget(self.radioButton_topright, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.Legend)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 0, 1, 1)
        self.checkBox_legend = QtWidgets.QCheckBox(self.Legend)
        self.checkBox_legend.setObjectName("checkBox_legend")
        self.gridLayout.addWidget(self.checkBox_legend, 0, 0, 1, 1)
        self.spinBox_fontsize = QtWidgets.QSpinBox(self.Legend)
        self.spinBox_fontsize.setProperty("value", 12)
        self.spinBox_fontsize.setObjectName("spinBox_fontsize")
        self.gridLayout.addWidget(self.spinBox_fontsize, 5, 1, 1, 1)
        self.radioButton_bottomleft = QtWidgets.QRadioButton(self.Legend)
        self.radioButton_bottomleft.setObjectName("radioButton_bottomleft")
        self.gridLayout.addWidget(self.radioButton_bottomleft, 2, 0, 1, 1)
        self.checkBox_Jsc = QtWidgets.QCheckBox(self.Legend)
        self.checkBox_Jsc.setObjectName("checkBox_Jsc")
        self.gridLayout.addWidget(self.checkBox_Jsc, 4, 0, 1, 1)
        self.radioButton_outside = QtWidgets.QRadioButton(self.Legend)
        self.radioButton_outside.setObjectName("radioButton_outside")
        self.gridLayout.addWidget(self.radioButton_outside, 3, 0, 1, 1)
        self.radioButton_bottomright = QtWidgets.QRadioButton(self.Legend)
        self.radioButton_bottomright.setObjectName("radioButton_bottomright")
        self.gridLayout.addWidget(self.radioButton_bottomright, 2, 1, 1, 1)
        self.checkBox_Eg = QtWidgets.QCheckBox(self.Legend)
        self.checkBox_Eg.setObjectName("checkBox_Eg")
        self.gridLayout.addWidget(self.checkBox_Eg, 4, 1, 1, 1)
        self.radioButton_best = QtWidgets.QRadioButton(self.Legend)
        self.radioButton_best.setChecked(True)
        self.radioButton_best.setObjectName("radioButton_best")
        self.gridLayout.addWidget(self.radioButton_best, 3, 1, 1, 1)
        self.pushButton_reorder = QtWidgets.QPushButton(self.Legend)
        self.pushButton_reorder.setObjectName("pushButton_reorder")
        self.gridLayout.addWidget(self.pushButton_reorder, 0, 1, 1, 1)
        self.tabWidget_right.addTab(self.Legend, "")
        self.EditLegend = QtWidgets.QWidget()
        self.EditLegend.setObjectName("EditLegend")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.EditLegend)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.scrollArea_legend = QtWidgets.QScrollArea(self.EditLegend)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_legend.sizePolicy().hasHeightForWidth())
        self.scrollArea_legend.setSizePolicy(sizePolicy)
        self.scrollArea_legend.setWidgetResizable(True)
        self.scrollArea_legend.setObjectName("scrollArea_legend")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 484, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_legend = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_legend.setObjectName("verticalLayout_legend")
        self.scrollArea_legend.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_5.addWidget(self.scrollArea_legend, 0, 0, 1, 1)
        self.tabWidget_right.addTab(self.EditLegend, "")
        self.verticalLayout_2.addWidget(self.splitter_2)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_8)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(12)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab_8, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.splitter)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.splitter_3 = QtWidgets.QSplitter(self.tab_7)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setHandleWidth(5)
        self.splitter_3.setObjectName("splitter_3")
        self.frame_3 = QtWidgets.QFrame(self.splitter_3)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mplwidgetLoss = QtWidgets.QWidget(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwidgetLoss.sizePolicy().hasHeightForWidth())
        self.mplwidgetLoss.setSizePolicy(sizePolicy)
        self.mplwidgetLoss.setObjectName("mplwidgetLoss")
        self.gridLayout_mplwidgetLoss = QtWidgets.QGridLayout(self.mplwidgetLoss)
        self.gridLayout_mplwidgetLoss.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_mplwidgetLoss.setSpacing(0)
        self.gridLayout_mplwidgetLoss.setObjectName("gridLayout_mplwidgetLoss")
        self.horizontalLayout_2.addWidget(self.mplwidgetLoss)
        self.frame_4 = QtWidgets.QFrame(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_4)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1046, 583))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tableWidget_detailsoflosses = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_detailsoflosses.sizePolicy().hasHeightForWidth())
        self.tableWidget_detailsoflosses.setSizePolicy(sizePolicy)
        self.tableWidget_detailsoflosses.setMinimumSize(QtCore.QSize(621, 141))
        self.tableWidget_detailsoflosses.setMaximumSize(QtCore.QSize(16777215, 141))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.tableWidget_detailsoflosses.setFont(font)
        self.tableWidget_detailsoflosses.setAutoFillBackground(False)
        self.tableWidget_detailsoflosses.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_detailsoflosses.setShowGrid(True)
        self.tableWidget_detailsoflosses.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget_detailsoflosses.setObjectName("tableWidget_detailsoflosses")
        self.tableWidget_detailsoflosses.setColumnCount(6)
        self.tableWidget_detailsoflosses.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_detailsoflosses.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_detailsoflosses.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_detailsoflosses.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_detailsoflosses.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_detailsoflosses.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_detailsoflosses.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_detailsoflosses.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_detailsoflosses.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_detailsoflosses.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_detailsoflosses.setHorizontalHeaderItem(5, item)
        self.tableWidget_detailsoflosses.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_detailsoflosses.horizontalHeader().setDefaultSectionSize(80)
        self.tableWidget_detailsoflosses.horizontalHeader().setMinimumSectionSize(60)
        self.tableWidget_detailsoflosses.verticalHeader().setVisible(False)
        self.tableWidget_detailsoflosses.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget_detailsoflosses.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget_detailsoflosses.verticalHeader().setHighlightSections(True)
        self.tableWidget_detailsoflosses.verticalHeader().setMinimumSectionSize(25)
        self.tableWidget_detailsoflosses.verticalHeader().setStretchLastSection(True)
        self.gridLayout_10.addWidget(self.tableWidget_detailsoflosses, 5, 2, 1, 2)
        self.tableWidget_zonesdefinition = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_2)
        self.tableWidget_zonesdefinition.setMinimumSize(QtCore.QSize(161, 141))
        self.tableWidget_zonesdefinition.setMaximumSize(QtCore.QSize(161, 141))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.tableWidget_zonesdefinition.setFont(font)
        self.tableWidget_zonesdefinition.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tableWidget_zonesdefinition.setObjectName("tableWidget_zonesdefinition")
        self.tableWidget_zonesdefinition.setColumnCount(2)
        self.tableWidget_zonesdefinition.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_zonesdefinition.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_zonesdefinition.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_zonesdefinition.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_zonesdefinition.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_zonesdefinition.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_zonesdefinition.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_zonesdefinition.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_zonesdefinition.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_zonesdefinition.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_zonesdefinition.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_zonesdefinition.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_zonesdefinition.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_zonesdefinition.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_zonesdefinition.setItem(3, 1, item)
        self.tableWidget_zonesdefinition.horizontalHeader().setDefaultSectionSize(50)
        self.tableWidget_zonesdefinition.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_zonesdefinition.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_zonesdefinition.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_zonesdefinition.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget_zonesdefinition.verticalHeader().setMinimumSectionSize(25)
        self.tableWidget_zonesdefinition.verticalHeader().setStretchLastSection(True)
        self.gridLayout_10.addWidget(self.tableWidget_zonesdefinition, 5, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pushButton_loadT = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_loadT.sizePolicy().hasHeightForWidth())
        self.pushButton_loadT.setSizePolicy(sizePolicy)
        self.pushButton_loadT.setObjectName("pushButton_loadT")
        self.gridLayout_9.addWidget(self.pushButton_loadT, 8, 3, 1, 1)
        self.checkBox_addtoMain = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_addtoMain.setEnabled(True)
        self.checkBox_addtoMain.setObjectName("checkBox_addtoMain")
        self.gridLayout_9.addWidget(self.checkBox_addtoMain, 10, 0, 1, 1)
        self.comboBox_R = QtWidgets.QComboBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_R.sizePolicy().hasHeightForWidth())
        self.comboBox_R.setSizePolicy(sizePolicy)
        self.comboBox_R.setObjectName("comboBox_R")
        self.gridLayout_9.addWidget(self.comboBox_R, 5, 1, 1, 1)
        self.comboBox_LAsamples = QtWidgets.QComboBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_LAsamples.sizePolicy().hasHeightForWidth())
        self.comboBox_LAsamples.setSizePolicy(sizePolicy)
        self.comboBox_LAsamples.setObjectName("comboBox_LAsamples")
        self.gridLayout_9.addWidget(self.comboBox_LAsamples, 1, 0, 1, 2)
        self.pushButton_loadR = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_loadR.sizePolicy().hasHeightForWidth())
        self.pushButton_loadR.setSizePolicy(sizePolicy)
        self.pushButton_loadR.setObjectName("pushButton_loadR")
        self.gridLayout_9.addWidget(self.pushButton_loadR, 5, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 5, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 8, 2, 1, 1)
        self.checkBox_R0 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_R0.setObjectName("checkBox_R0")
        self.gridLayout_9.addWidget(self.checkBox_R0, 5, 0, 1, 1)
        self.comboBox_T = QtWidgets.QComboBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_T.sizePolicy().hasHeightForWidth())
        self.comboBox_T.setSizePolicy(sizePolicy)
        self.comboBox_T.setObjectName("comboBox_T")
        self.gridLayout_9.addWidget(self.comboBox_T, 8, 1, 1, 1)
        self.label_pathToR = QtWidgets.QLabel(self.frame_2)
        self.label_pathToR.setObjectName("label_pathToR")
        self.gridLayout_9.addWidget(self.label_pathToR, 6, 0, 1, 4)
        self.pushButton_lossupdate = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_lossupdate.setObjectName("pushButton_lossupdate")
        self.gridLayout_9.addWidget(self.pushButton_lossupdate, 10, 3, 1, 1)
        self.checkBox_T0 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_T0.setChecked(True)
        self.checkBox_T0.setObjectName("checkBox_T0")
        self.gridLayout_9.addWidget(self.checkBox_T0, 8, 0, 1, 1)
        self.radioButton_fullareaEQE = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_fullareaEQE.setObjectName("radioButton_fullareaEQE")
        self.gridLayout_9.addWidget(self.radioButton_fullareaEQE, 2, 0, 1, 1)
        self.radioButton_spotEQE = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_spotEQE.setChecked(True)
        self.radioButton_spotEQE.setObjectName("radioButton_spotEQE")
        self.gridLayout_9.addWidget(self.radioButton_spotEQE, 2, 1, 1, 1)
        self.pushButton_loadOtherEQE = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_loadOtherEQE.setObjectName("pushButton_loadOtherEQE")
        self.gridLayout_9.addWidget(self.pushButton_loadOtherEQE, 2, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_9.addWidget(self.label_9, 4, 0, 1, 4)
        self.label_pathToOtherEQE = QtWidgets.QLabel(self.frame_2)
        self.label_pathToOtherEQE.setObjectName("label_pathToOtherEQE")
        self.gridLayout_9.addWidget(self.label_pathToOtherEQE, 3, 0, 1, 4)
        self.label_pathToT = QtWidgets.QLabel(self.frame_2)
        self.label_pathToT.setObjectName("label_pathToT")
        self.gridLayout_9.addWidget(self.label_pathToT, 9, 0, 1, 4)
        self.zonesoverlays = QtWidgets.QCheckBox(self.frame_2)
        self.zonesoverlays.setObjectName("zonesoverlays")
        self.gridLayout_9.addWidget(self.zonesoverlays, 10, 1, 1, 2)
        self.gridLayout_10.addWidget(self.frame_2, 0, 1, 1, 2)
        self.tableWidget_Losses = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_Losses.sizePolicy().hasHeightForWidth())
        self.tableWidget_Losses.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget_Losses.setFont(font)
        self.tableWidget_Losses.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_Losses.setDragDropOverwriteMode(False)
        self.tableWidget_Losses.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_Losses.setShowGrid(False)
        self.tableWidget_Losses.setObjectName("tableWidget_Losses")
        self.tableWidget_Losses.setColumnCount(4)
        self.tableWidget_Losses.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget_Losses.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Losses.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Losses.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Losses.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Losses.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setStrikeOut(False)
        font.setKerning(True)
        item.setFont(font)
        self.tableWidget_Losses.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Losses.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Losses.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Losses.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Losses.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Losses.setHorizontalHeaderItem(3, item)
        self.tableWidget_Losses.horizontalHeader().setDefaultSectionSize(80)
        self.tableWidget_Losses.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget_Losses.verticalHeader().setMinimumSectionSize(25)
        self.tableWidget_Losses.verticalHeader().setStretchLastSection(True)
        self.gridLayout_10.addWidget(self.tableWidget_Losses, 0, 3, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_11.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.splitter_3)
        self.tabWidget_2.addTab(self.tab_7, "")
        self.gridLayout_12.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1027, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSession = QtWidgets.QMenu(self.menubar)
        self.menuSession.setObjectName("menuSession")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_DATA = QtWidgets.QAction(MainWindow)
        self.actionImport_DATA.setObjectName("actionImport_DATA")
        self.actionExport_Graph_DATA = QtWidgets.QAction(MainWindow)
        self.actionExport_Graph_DATA.setObjectName("actionExport_Graph_DATA")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionExport_All_DATA = QtWidgets.QAction(MainWindow)
        self.actionExport_All_DATA.setObjectName("actionExport_All_DATA")
        self.actionSave_to_DB = QtWidgets.QAction(MainWindow)
        self.actionSave_to_DB.setObjectName("actionSave_to_DB")
        self.actionExport_Table_data = QtWidgets.QAction(MainWindow)
        self.actionExport_Table_data.setObjectName("actionExport_Table_data")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.menuFile.addAction(self.actionImport_DATA)
        self.menuFile.addAction(self.actionExport_Graph_DATA)
        self.menuFile.addAction(self.actionExport_Table_data)
        self.menuSession.addAction(self.actionSave)
        self.menuSession.addAction(self.actionLoad)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSession.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_left.setCurrentIndex(0)
        self.tabWidget_right.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EQE"))
        self.pushButton_loadspectrum.setText(_translate("MainWindow", "Load spectrum"))
        self.label_12.setText(_translate("MainWindow", "Current spectrum loaded:"))
        self.tabWidget_left.setTabText(self.tabWidget_left.indexOf(self.spectrum), _translate("MainWindow", "Spectrum"))
        self.label_5.setText(_translate("MainWindow", "Xmin"))
        self.label_6.setText(_translate("MainWindow", "Xmax"))
        self.label_8.setText(_translate("MainWindow", "Ymax"))
        self.label_7.setText(_translate("MainWindow", "Ymin"))
        self.checkBox_AutoScale.setText(_translate("MainWindow", "Auto-scaling"))
        self.comboBox.setItemText(0, _translate("MainWindow", "linear"))
        self.comboBox.setItemText(1, _translate("MainWindow", "log"))
        self.comboBox.setItemText(2, _translate("MainWindow", "NormalizedByAll"))
        self.comboBox.setItemText(3, _translate("MainWindow", "NormalizedBySingle"))
        self.tabWidget_left.setTabText(self.tabWidget_left.indexOf(self.Range), _translate("MainWindow", "Range"))
        self.pushButton_SGFilter.setText(_translate("MainWindow", "SavitzkyGolayFilter"))
        self.pushButton_goback.setText(_translate("MainWindow", "GoBack"))
        self.tabWidget_left.setTabText(self.tabWidget_left.indexOf(self.tab), _translate("MainWindow", "SGfilter"))
        self.pushButton_CalcCurrent.setText(_translate("MainWindow", "Calc. Current"))
        self.label_2.setText(_translate("MainWindow", "Between"))
        self.label_3.setText(_translate("MainWindow", "and"))
        self.label_4.setText(_translate("MainWindow", "Calculated current:"))
        self.tabWidget_left.setTabText(self.tabWidget_left.indexOf(self.tab_3), _translate("MainWindow", "CalcCurrent"))
        self.pushButton_stitchEQEs.setText(_translate("MainWindow", "Stitch EQEs"))
        self.checkBox_showsecreteg.setText(_translate("MainWindow", "ShowSecretEg"))
        self.tabWidget_left.setTabText(self.tabWidget_left.indexOf(self.tab_2), _translate("MainWindow", "others"))
        self.tabWidget_right.setTabText(self.tabWidget_right.indexOf(self.Selection), _translate("MainWindow", "Selection"))
        self.radioButton_topleft.setText(_translate("MainWindow", "TopLeft"))
        self.radioButton_topright.setText(_translate("MainWindow", "TopRight"))
        self.label.setText(_translate("MainWindow", "Fontsize"))
        self.checkBox_legend.setText(_translate("MainWindow", "legend?"))
        self.radioButton_bottomleft.setText(_translate("MainWindow", "BottomLeft"))
        self.checkBox_Jsc.setText(_translate("MainWindow", "Jsc"))
        self.radioButton_outside.setText(_translate("MainWindow", "Outside"))
        self.radioButton_bottomright.setText(_translate("MainWindow", "BottomRight"))
        self.checkBox_Eg.setText(_translate("MainWindow", "Eg"))
        self.radioButton_best.setText(_translate("MainWindow", "Best"))
        self.pushButton_reorder.setText(_translate("MainWindow", "Reorder"))
        self.tabWidget_right.setTabText(self.tabWidget_right.indexOf(self.Legend), _translate("MainWindow", "Legend"))
        self.tabWidget_right.setTabText(self.tabWidget_right.indexOf(self.EditLegend), _translate("MainWindow", "Edit Legend"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Plot options"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "sample"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "batch"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "sample#"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "date/time"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "meas. type"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Jsc from file"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Jsc recalc."))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Eg0"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "EgIP"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "EgTauc"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "EgLn"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "EuLn"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Results table"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Plotting"))
        item = self.tableWidget_detailsoflosses.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Zone 1"))
        item = self.tableWidget_detailsoflosses.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Zone 2"))
        item = self.tableWidget_detailsoflosses.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Zone 3"))
        item = self.tableWidget_detailsoflosses.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Full"))
        item = self.tableWidget_detailsoflosses.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "EQEfull"))
        item = self.tableWidget_detailsoflosses.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "EQEspot"))
        item = self.tableWidget_detailsoflosses.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "IQE"))
        item = self.tableWidget_detailsoflosses.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "1-R-T"))
        item = self.tableWidget_detailsoflosses.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "1-R"))
        item = self.tableWidget_detailsoflosses.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "flux"))
        item = self.tableWidget_zonesdefinition.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Zone 1"))
        item = self.tableWidget_zonesdefinition.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Zone 2"))
        item = self.tableWidget_zonesdefinition.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Zone 3"))
        item = self.tableWidget_zonesdefinition.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Full"))
        item = self.tableWidget_zonesdefinition.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "From"))
        item = self.tableWidget_zonesdefinition.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "To"))
        __sortingEnabled = self.tableWidget_zonesdefinition.isSortingEnabled()
        self.tableWidget_zonesdefinition.setSortingEnabled(False)
        item = self.tableWidget_zonesdefinition.item(0, 0)
        item.setText(_translate("MainWindow", "300"))
        item = self.tableWidget_zonesdefinition.item(0, 1)
        item.setText(_translate("MainWindow", "600"))
        item = self.tableWidget_zonesdefinition.item(1, 0)
        item.setText(_translate("MainWindow", "600"))
        item = self.tableWidget_zonesdefinition.item(1, 1)
        item.setText(_translate("MainWindow", "1200"))
        item = self.tableWidget_zonesdefinition.item(2, 0)
        item.setText(_translate("MainWindow", "1000"))
        item = self.tableWidget_zonesdefinition.item(2, 1)
        item.setText(_translate("MainWindow", "1200"))
        item = self.tableWidget_zonesdefinition.item(3, 0)
        item.setText(_translate("MainWindow", "300"))
        item = self.tableWidget_zonesdefinition.item(3, 1)
        item.setText(_translate("MainWindow", "1200"))
        self.tableWidget_zonesdefinition.setSortingEnabled(__sortingEnabled)
        self.pushButton_loadT.setText(_translate("MainWindow", "Load transmittance"))
        self.checkBox_addtoMain.setText(_translate("MainWindow", "add to MainDATA"))
        self.pushButton_loadR.setText(_translate("MainWindow", "Load reflectance"))
        self.label_10.setText(_translate("MainWindow", "or"))
        self.label_11.setText(_translate("MainWindow", "or"))
        self.checkBox_R0.setText(_translate("MainWindow", "Define R=0"))
        self.label_pathToR.setText(_translate("MainWindow", "path for R..."))
        self.pushButton_lossupdate.setText(_translate("MainWindow", "Update"))
        self.checkBox_T0.setText(_translate("MainWindow", "Define T=0"))
        self.radioButton_fullareaEQE.setText(_translate("MainWindow", "Full-ara EQE"))
        self.radioButton_spotEQE.setText(_translate("MainWindow", "spot EQE"))
        self.pushButton_loadOtherEQE.setText(_translate("MainWindow", "Load other EQE type"))
        self.label_9.setText(_translate("MainWindow", "Note: Reflectance and Transmittance are spot-area (between fingers)"))
        self.label_pathToOtherEQE.setText(_translate("MainWindow", "path to other EQE type if imported"))
        self.label_pathToT.setText(_translate("MainWindow", "Path for T..."))
        self.zonesoverlays.setText(_translate("MainWindow", "Zones overlays"))
        item = self.tableWidget_Losses.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Total current (full area EQE)"))
        item = self.tableWidget_Losses.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Total current (spot EQE)"))
        item = self.tableWidget_Losses.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Metallization shading"))
        item = self.tableWidget_Losses.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Transmission loss"))
        item = self.tableWidget_Losses.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Reflection loss"))
        item = self.tableWidget_Losses.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "other losses, e.g. parasitic abs., collection..."))
        item = self.tableWidget_Losses.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Total loss"))
        item = self.tableWidget_Losses.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Zone1"))
        item = self.tableWidget_Losses.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Zone2"))
        item = self.tableWidget_Losses.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Zone3"))
        item = self.tableWidget_Losses.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Total"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "Loss analysis"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSession.setTitle(_translate("MainWindow", "Session"))
        self.actionImport_DATA.setText(_translate("MainWindow", "Import DATA"))
        self.actionExport_Graph_DATA.setText(_translate("MainWindow", "Export Graph/DATA"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionExport_All_DATA.setText(_translate("MainWindow", "Export All DATA"))
        self.actionSave_to_DB.setText(_translate("MainWindow", "Save to DB"))
        self.actionExport_Table_data.setText(_translate("MainWindow", "Export Table data"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))

